### ISSUE TITLE
Computer name is set to natasha in code

### ISSUE THREAD

**Issue by KarthikNayak** [rahulraghu94/rShell#1]

**Comment by rahulraghu94** [comment]
Wow, i had forgotten about this!
Will fix :)
Although i remember it priniting random hex values when i tried to set it as per user wishes

**Comment by KarthikNayak** [comment]
could you do `cat /etc/hostname` and let me know?

**Comment by niteshjain** [comment]
Wouldn't it be better to use gethostname() ?

**Comment by KarthikNayak** [comment]
@niteshjain That's definitely a better way to go ahead with this :+1:

**Comment by rahulraghu94** [comment]
Ah alright, will do it!

**Comment by rahulraghu94** [comment]
Prints correct host names now. Thanks for reintroducing me to this little project and for the help :D
